# Preface {#preface .unnumbered}

> We shall not cease from exploration
>
> And the end of all our exploring
>
> Will be to arrive where we started
>
> And know the place for the first time.

::: flushright
--- T.S. Eliot, *Little Gidding*
:::

I began writing this book in 2018. At that time, data science was a relatively new field and data science degree programs were just beginning to emerge. Pioneering data science programs at University of California Berkeley and New York University emerged in the 2010s; the BA in Statistics and Data Science at the University of Colorado Boulder (CU Boulder)---my home institution at the time of this writing---launched in 2018, with the launch of the MS in Data Science in fall 2021.

At CU Boulder, like most universities, statistics---alongside computing and domain knowledge---is one of three foundational pillars of data science programs. Thus, the explosion of data science meant an explosion in the engagement with, and application of, statistical methods. But use of statistics does not equate to *correct use* of statistics. The rise of data science correlated with a rise of various misinterpretations and misuses of statistics. One goal of this book is to help statistics and data science students engage with statistical concepts and reasoning on a deeper level, to distinguish between correct and incorrect uses of statistics. Another goal is more ambitious: to encourage those who are not students of statistics to see the discipline, not as a branch of math, or even a technical field, but as conceptually rich and interesting. Thus, this book may also be of interest to anyone curious about philosophy or science.

This approach is not always present in statistics education. Statistics courses often present statistics as a sub-discipline of math, and teach statistical methods as "recipes" for producing inferences. But, in my view, it is much less common that statistics courses engage in the philosophical, conceptual, and inferential underpinnings clearly threaded through the discipline. I believe it is this kind of engagement that makes one a stronger statistical thinker, and user of statistics.

As a pillar of data science, statistics is of instrumental value. Statistics helps practitioners---scientists, domain experts---answer research and business questions. Now, in the age of AI, where methods and "recipes" can be automated, it's worth considering whether statistics has some deeper, perhaps intrinsic, value. Why study statistics if computers can deploy methods on our behalf? I believe that there is still value in studying statistics. Statistics is about inference. And to infer is deeply human. As a human endeavor, inference is messy. Philosophers and statisticians are in deep disagreement about the nature of inference; about how we go from "what?" to "why?" [@pearl_mackenzie_2018]. A deeper study and engagement with philosophical questions may help us gain clarity on the nature of inference. For those of us with some familiarity with statistics, this deeper engagement may help us "arrive where we started" in our statistics journeys, and "know the place for the first time."

## Arriving where I started and Acknowledgements

My high school was relatively strange, at least for United States standards. It employed an English teacher who taught two philosophy courses. I think I had some vague idea of what philosophy was, mostly from seeing the 2001 Richard Linklater film *Waking Life*. What vague idea I had intrigued me. So, in my senior year of high school, when a sizable portion of peers took AP classes for college readiness, and another sizable portion left school a period early, I took Introduction to Western Philosophy with Ms. Cathy Pentola. As I remember it, the course was a broad overview of the history of philosophy, from Plato to the twentieth century existentialist Jean-Paul Sartre. Ms. Pentola was a formative influence on me. She was curious. She made learning exciting. For that hour, ideas mattered. My first experience with philosophy changed my life.

And yet, with a mother in healthcare; a father in ski area operations; a step father working as a yardmaster for the railroad; and a brother training to be a physical education teacher, I had no map for where philosophy training might lead. In high school, my mother nudged me toward math and engineering. I performed well on the New York State Regents Exams in Mathematics, so I decided to major in math. I started at Manhattan College (now Manhattan University). As a liberal arts college, I took courses in western civilization and world religions. I was exposed to math, but also to the wonderful strangeness of a liberal Christian education (wonderful and strange because many of the De La Salle Christian Brothers were as excited about learning as Ms. Pentola, and as open-minded and critical as anyone I had met up to that point). My time at Manhattan was short; just one year. I was an aspiring musician trying to get a record deal with my high school band. So I transferred to the State University of New York Stony Brook, to be closer to home. Needless to say, no record deal.[^1]

Stony Brook had both a Department of ("pure") Mathematics and a Department of Applied Mathematics. Primarily, I studied in the former. I thought there was something edgy to being a pure math major. But pure math was also strangely philosophical. Infinity. Proof and truth. Undecidability. Platonism, formalism, logicism. The strangeness of application. The philosophical kept me going.

At the same time, I took philosophy courses. Existentialism and Nietzsche with David Allison. Philosophy of Science with Robert Crease. Philosophy of Mathematics with Gary Mar. Kierkegaard with Peter Manchester. Heidegger with Tim Hyde. I slowly built up a second major in philosophy. Peter Manchester would say that, when he was deciding between becoming a mathematician or a philosopher, he learned that mathematicians peak in their 20s and philosophers in their 60s. So, he went with philosophy. Why burn out early?

I loved academics so much that I enrolled in the fall 2007 semester at Stony Brook, even thought by summer of that year, I had all the credits I needed to graduate. I enrolled in two courses. One was a graduate-level abstract algebra course. It was absolutely brutal, and I only passed it by arguing, somehow, to retake the final exam. The other was a special topics course in philosophy, which the catalog said would be on postmodernism. I remember years before trying to learn what "postmodernism" meant, and failing, but I thought I'd give it a shot. When I arrived late on the first day, I quickly realized that the class wasn't on postmodernism, but on Martin Heidegger's *Being and Time*. I hadn't read Heidegger, but knew of his influence on my then-hero Sartre. That semester changed my life. Stony Brook's Philosophy Department was decidedly "continental": most of the faculty had expertise in philosophers from the continent of Europe (e.g., Germany, France). To be overly simplistic, as continental philosophers, they were interested in questions related to the meaning of *life* not the meaning of *language* or *science*. I was sold on continental philosophy.

During that semester, while seeking help with my Heidegger reading, I discovered American philosopher Hubert Dreyfus' podcasts: on Heidegger's *Being and Time*; on his view of existentialism, which did not include Sartre, but instead Dostoevsky; on the western classics from *The Odyssey* and *The Gospel of John* to *Mobey Dick*. Dreyfus made both philosophy and teaching exciting and approachable. Although older and influenced by Heidegger's skepticism of modern technology, he embraced the 2000s podcast craze. I listened to Dreyfus on repeat in 2007 and 2008, from Port Jefferson, NY to the mountains of Colorado. I still listen to some of his lectures from time to time, and think often of his book (with coauthor Sean Kelly) *All Things Shining*.

In all of this engagement with math and philosophy, *philosophy of statistics* was not on my radar. In all of my undergraduate work, I took only two courses related to probability and statistics: one in probability theory, and another, in the Department of Applied Math, in random processes. Neither made a major impression on me.

In early 2008, I joined AmeriCorps National Civilian Community Corps and served on a wild-land firefighting team in Colorado. I loved it. The physicality, the dirt, the mountains. One time, my crew actually started a fire (legally: it was a controlled burn to protect the area against a large wild fire). I applied and was accepted to be a fire crew team leader for the next year. But I knew that I would not be fulfilled without a steady and sustained engagement with ideas. So, I applied to graduate school in philosophy. I was admitted to (and only to) the PhD program at the University of South Carolina, in 2009. I spent two years there trying to learn about Heidegger---and succeeding, but mainly because of Dreyfus in my ear, my side reading, and discussions with my brilliant and cherished friend Michael Glawson.

In 2009, I presented a paper titled "Cultural Objects in Carnap's Aufbau: a Heideggerian Critique" at the South Carolina Society for Philosophy. Afterward, I was approached by someone asking me what I thought of Heidegger on X, Y, and Z. He was very curious and kind. Later that day, I learned from one of my professors that I was talking to Julian Young, a distinguished Heidegger and Nietzsche scholar at Wake Forest University. Young and I kept in touch for a few years. He graciously invited me to a continental philosophy reading group in the area. A year or so later, Young invited Dreyfus to visit and give a talk on *All Things Shining*. Amazingly, Michael Glawson and I attended the talk, another seminar, and had steak dinner with Young and Dreyfus. A true career highlight. All of these events propelled me further in the direction of continental philosophy.

However, in my courses at South Carolina, instead of learning about continental philosophy, I was learning about the history of philosophy, philosophy of science, and the philosophy of statistics (though I didn't know it by that name at the time). In my first semester, I was a teaching assistant for a course in inductive logic, under the philosopher of physics Professor Michael Dickson. This course fulfilled a math requirement for arts and science majors; it was basically a statistics course, but focused on fundamental issues in inference, interpretations of probability, paradoxes, and Bayesian reasoning. I had no idea that statistics could be so philosophically rich (of course now this strikes me as naïve). I learned much from Michael Dickson about philosophy of science and statistics. He was a fantastic mentor (both in philosophy and briefly in triathlon). But still under the sway of Heidegger, I did not realize that the philosophy of statistics was something that I wanted to study more seriously.

I made one last push to study continental philosophy, applying to schools with a strong reputation in Heidegger studies. At the same time, some faculty at South Carolina were making one last push for me to put my math background to use in a dissertation on philosophy of science and applied mathematics. Why do you care about Dostoevsky? That's not philosophy!

Knowing the realities of the recession economy in 2010, and the job market for philosophers (even in good years), I also decided that, in addition to several top tier continental philosophy PhD programs, I would apply to two applied math PhD programs. These were safety schools, so that if I didn't get into my reach schools in philosophy, I'd have a more "practical" path forward. As luck would have it, I wasn't granted admission to any schools in philosophy, but was offered the opportunity to study applied math at the Colorado School of Mines. I loved Colorado, so the pain of rejection in philosophy was offset by the Rocky Mountains.

Colorado School of Mines is primarily an engineering school. There are relatively few faculty who work in the humanities. The summer before moving to Colorado, I cold-emailed Professor Carl Mitcham, one of only two philosophers at Mines in 2011. Carl responded with excitement. We talked on the phone the next day, and he helped me secure funding to work with their liberal arts group while pursuing my PhD in Applied Mathematics and Statistics. At Mines, with Carl and his colleagues, I began to learn an about teaching philosophy to STEM students.

Carl is a renowned philosopher of technology and helped cultivate and grow the field of science and technology studies. He, like Dreyfus, taught with excitement, from his heart. In one introduction to ethics course, I remember Carl being moved almost to tears teaching Kant's *Grounding of the Metaphysics of Morals*, and specifically Kant's claim that "Nothing in the world---or out of it!---can possibly be conceived that could be called 'good' without qualification except a GOOD WILL." Carl challenged my consequentialist intuitions, that ethics is primarily about pleasure and pain. There is something more; something good in us, worthy of great respect, independent of the consequences. To this day, Carl, who is not only a mentor but a great friend, is tirelessly fair, even to those with whom he may have deep philosophical or personal disagreements. I try (to varying degrees of success) to emulate Carl's hermeneutics of charity, and his presumption that the human will we are presented with is *Good*, worthy of being heard and respected.

After a year of being more interested in philosophy than partial differential equations, I finally made my way to the statistics faculty at Mines. I began connecting my philosophy of science interests with my PhD coursework. I was learning how faculty and practicing statisticians think about the philosophical differences in their own disciplines. Debates between faculty were sometimes contentious. I enjoyed those debates more than my courses.

My PhD research project came to me by luck. Mathematician and National Renewable Energy Lab[^2] post-doc Mark Campanelli connected briefly with my soon-to-be advisor Luis Tenorio about a solar cell performance modeling project. Luis announced this opportunity at a department orientation, and I rushed him afterwards. If I was going to do something unrelated to philosophy, it might as well contribute to some good cause (and renewable energy sounded good enough to me). Luis, Mark, and my co-advisor Paul Constantine encouraged me (or at least did not *discourage* me) to think philosophically in the context of a real and difficult problem. Ultimately, to no fault of my advisors or collaborators, my PhD work at Mines was mediocre. I was not a fantastic statistics researcher. But I did enough to pass my dissertation exam. Perhaps I convinced the committee that I knew *something* about research. But primarily, I think I convinced them that I would be a strong teacher, and a generalist that could be an asset to another university.

In 2015, after around 15 applications and five or so interviews, I landed an Instructor position at the University of Colorado Boulder's (CU Boulder) Department of Applied Mathematics (APPM). It was not clear to me how this role would take shape or what my niche would be. I was mainly hired to teach calculus and linear algebra, which was satisfying enough. I quickly became involved in APPM's nascent statistics and data science efforts. I helped propose the BA in Statistics and Data Science to the Board of Regents. Soon after, drawing on ideas from Michael Dickson's inductive logic course, and onversations with Carl, my advisors, and others, I proposed a course in the philosophy of statistics. To my shock, then Chair Keith Julien and Associate Chair Anne Dougherty approved of this idea. APPM was, and still is, very supportive of teaching faculty proposing new courses in their areas of interest. This course has evolved a lot over the last several years and helped me shape the trajectory of this book.

In additional to APPM, I am also indebted to CU Boulder philosopher of science Carol Cleland for helping me with early ideas for my course and this book. In 2016, I attended her philosophy of science course, where she introduced me to the work of philosopher of statistics Deborah Mayo. As you will see if you read on, Mayo's work has been influential to my thinking about foundational debates in statistics. In 2019, I was accepted into the Summer Seminar in Philosophy of Statistics, hosted by Mayo and her collaborator Aris Spanos. In a world of growing interest in Bayesian methods, I learned to appreciate the virtues of frequentist inference. Mayo's and Spanos' work is still under-appreciated for the extent to which it strengthens the conceptual and philosophical foundations of frequentist inference. I met many wonderful people at this seminar, including Georgi Gardiner, who later graciously invited me to collaborate on a paper collecting some of her research with Mayo's work [@gardiner2022safe]. Thanks, Georgi!

In 2018, I started writing the first chapter of this book. I distinctly remember working on parts of it at the Joint Statistical Meetings in Vancouver, British Columbia. I had my first coffee a few months earlier that year (at 33 years old!), and decided: why not have another? A student at the time, Gregory Benton, suggested a cold brew at a fancy Vancouver coffee shop. I wrote vigorously that day, and was up half the night! Greg, thank you for the great conversations about statistics and philosophy that helped form the early ideas for this book. Also, thanks being someone to talk with about sad music and mildly edgy podcasts, and for the companionship in Vancouver.

I owe no one a bigger thanks than Ian Van Buskirk. Ian endured my teaching in philosophy of statistics and introduction to mathematical statistics---both in the same semester, fall 2019. We have since become good friends, colleagues, and coauthors. Ian's diverse and singular background made him an ideal conversation partner during formative writing years. He read draft chapters, served as a student assistant for my philosophy of statistics course, and helped me make slow but steady writing progress. Ian, thanks for keeping me honest, full of Montreal bagels and May Wah, and for being such a good friend.

I am also indebted to the brilliant Alison Weinberger. Alison was a philosophy and math major at CU Boulder, now a PhD candidate in philosophy. She helped challenge me and shaped many of my ideas. When the COVID pandemic hit, Alison and I (and others) started a remote reading group, and would sometimes meet for outdoor coffee to keep up conversations on everything from philosophy of statistics to existentialism. Alison, thanks for the fantastic questions and encouragement!

Thank you to my wife, Becca, for encouraging me to finish this project, even when I was thoroughly discouraged with how slow I was going. Sorry for all the time away at coffee shops! And thank you to our friend Elyse, for joining me at those coffee shops to work and write together. Bzz!

Thank you to my family---my mother for being an unwavering support throughout. well, my entire life; my brother for the laughs, encouragement, breaks for hikes and hockey, and paving the way as the first author in the family; and to my step father for being proud of whatever I'd produce.\
\
Now you all have to read this??

## How I used AI in this book

The majority of this book was written---and parts posted to the web in various places---before AI became widely available. My view is that writing is a human activity, and one that makes one's mind and one's views sharper. To hand that activity over to a computer is to miss the point of what writing can and ought to be. Maybe one day that view will seem quaint.

Nothing in this book was written by AI. With that said, I did use AI (primarily ChatGPT) in the following ways:

- To explore some possible citations for an argument or description that I was giving (e.g., "I think person X used the following analogy, but I can't remember the citation. Help?")

- To generate BibTex code for citations.

- To test some of my ideas and arguments in @sec-probability and @sec-frequentist, to generate one example in @sec-probability, and for proofreading. For example, in a few occasions, I gave ChatGPT my account of someone's position and asked whether it was a fair characterization. I was hesitant to do any of these things with AI. But, unfortunately, in 2024, my primary conversation partner (Ian) finished his PhD and moved back east, and very few colleagues or other students were available to discuss some of these niche topics. With that said, the sycophantic nature of AI made it such that I did not always gain from these exchanges.

- To help convert my original writing format---LaTeX---to a web book. ChatGPT helped me write documents to use Pandocs to convert LaTeXto Markdown, and ultimately to a Quarto web book. These are tasks that have no real value to me beyond their finished product, and I happily surrendered them to AI!

- To help with website copy. I am not in marketing. I had a set of ideas about how this book fits into the new AI landscape. I shared those ideas with ChatGPT to help move away from my more academic tone and toward something with more of a hook.

[^1]: But our 2004 and 2005 releases somehow made it onto Apple Music and Spotify! <https://music.apple.com/us/artist/sgt/74262310>

[^2]: Now the National Lab of the Rockies.
